### ISSUE TITLE
Issue !!!

### ISSUE THREAD

**Issue by pbenaim** [alpinechough/Alpinechough.Srtm#1]
Work very well when coordonnees are positive ( North and Est ) :-)

But bug when we are in négative positions ( like South or/and West ) :-(

I have always ArgumentOutOfRangeException error :-(

I tried to do something in : public int GetHeight (IGeographicalCoordinates coordinates)

with something like:

int localLat = (int)(Math.Abs(coordinates.Latitude - Latitude) * PointsPerCell);
int localLon = (int)((Math.Abs(coordinates.Longitude - Longitude)) * PointsPerCell);

But no Way, the result is now without ArgumentOutOfRangeException :-) but the result is wrong !!!!

I had tested, too when localLat or localLon is < 0 to say localLat or localLon is 1-localX, but no ArgumentOutOfRangeException too, but the result is not good... Grrrr.

Can you help me to resolve, when coordinates are negatives ?

In french, we can say: Au secours !!!!

Best Regards.

Philippe

**Comment by pbenaim** [comment]
Find :-)

in Srtm.cs
in GetHeight

must be = 

            int cellLatitude = (int)Math.Floor (Math.Abs (coordinates.Latitude));
            if (coordinates.Latitude < 0)
            {
                cellLatitude *= -1;
                cellLatitude -= 1; // because negative so in bottom tile
            }
	    int cellLongitude = (int)Math.Floor (Math.Abs (coordinates.Longitude));
            if (coordinates.Longitude < 0)
            {
                cellLongitude *= -1;
                cellLongitude -= 1; // because negative so in left tile
            }

Enjoy, and thanks for yur job

**Comment by alpinechough** [comment]
Thank you for your contribution.
