### ISSUE TITLE
Negative coordonnées

### ISSUE THREAD

**Issue by pbenaim** [alpinechough/Alpinechough.Srtm#2]
in SrtmDataCell 

You changed

if (filename.Contains ("s"))
{
	Latitude *= -1;
	Latitude += 1;
}
			
if (filename.Contains ("w"))
{
	Longitude *= -1;
	Longitude += 1;
}

But must stay like original !!! :

if (filename.Contains ("s"))
    Latitude *= -1;
			
if (filename.Contains ("w"))
   Longitude *= -1;

The change is only in GetHeight / SrtmData .

Best Regards

**Comment by alpinechough** [comment]
Hello,
you're right...

I tried using "Machu Picchu" (-13.163333, -72.545556) and it did not work out... - I know discovered, that there is no elevation for these coordinates (0x80, 0x00). I introduced the nullable value to cover this.

Thx again for your support!
